### ISSUE TITLE
start container failed，iptables: No chain/target/match by that name

### ISSUE THREAD

**Issue by goodryb** [xwjdsh/2048-ai#1]
[root@host ~]# docker run -p 8080:8080 wendellsun/2048-ai
	Unable to find image 'wendellsun/2048-ai:latest' locally
	latest: Pulling from wendellsun/2048-ai
	a52c7d714e5f: Pull complete
	15e0dc04655d: Pull complete
	f2435a32f659: Pull complete
	bdf9109f7f82: Pull complete
	9d85d078285a: Pull complete
	9cc6c519d7ab: Pull complete
	7537db3001ad: Pull complete
	0a11135497c2: Pull complete
	8678b49e634e: Pull complete
	Digest: sha256:82bff73de628bf2fd14f345636937e374e3afdf0f8773dec38776df50fd7b1e2
	Status: Downloaded newer image for wendellsun/2048-ai:latest
	Error response from daemon: Cannot start container c26c446a7e8ce4a970e976fd0f2c7ca4e165a4534af350d143a0a5603caa116e: iptables failed: iptables -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 -j DNAT --to-destination 192.168.42.2:8080 ! -i docker0: iptables: No chain/target/match by that name.
	 (exit status 1)

**Comment by xwjdsh** [comment]
Thanks for your feedback, but I can't recur this issue.
I guess its may cause by your server config rather than my docker images.  

The follow link maybe help you.
https://github.com/moby/moby/issues/16816

**Comment by Freebase394** [comment]
i have downloaded right now ant everithing is OK
![image](https://user-images.githubusercontent.com/19652056/93005532-c2edbf00-f549-11ea-8650-724d76f22fa8.png)
