### ISSUE TITLE
docker is error

### ISSUE THREAD

**Issue by sunnyregion** [xwjdsh/2048-ai#3]
docker build -t 2048-ai .
Sending build context to Docker daemon 1.698 MB
Step 1/12 : FROM golang:1.9 as builder
Error parsing reference: "golang:1.9 as builder" is not a valid repository/tag: invalid reference format

My golang version is go version go1.9.2 linux/amd64
OS is Ubuntu 16.04

**Comment by xwjdsh** [comment]
The Dockerfile using Docker multi-stage builds feature, it requiring Docker version 17.05 or higher, you can access following link get more.

https://docs.docker.com/engine/userguide/eng-image/multistage-build/
